gpu: "0"
dir: "runs"
name: "feddare_experiment"
save: "true"
dataset: "cifar10"
iid-alpha: 0.1
clients: 100
model: "vit_b_16"
seed: 0

# Evaluation settings
eval-freq: 10
eval-first: "false"
eval-frac: 1.0
eval-masked: "true"

# Server settings
server-opt: "adam"
server-lr: 1.0e-3
server-batch: 10
server-rounds: 100
server-freeze: "false"

# Client settings
client-lr: 1.0e-3
client-batch: 16
client-epochs: 1
client-freeze: "false"

# LoRA settings
freeze-a: "false"
lora-rank: 16
lora-alpha: 16

# FL settings
fl_strategy: ""

# Privacy settings
l2-clip-norm: 0.0
noise-multiplier: 0.0

# Logging settings
use_wandb: true
use_tensorboard: true
project_name: "federated_merging"
entity: null

# Merging strategy
merging_strategy: "feddare"
merging_kwargs:
  p_drop: 0.5